[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --chip esp32s3"

[target.'cfg(target_arch = "xtensa")']
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

[unstable]
build-std = ["core", "alloc"]
#build-std = ["core"]

[env]
ESP_LOG="info"
